config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :tournaments, only: [:index, :show, :create, :update, :destroy]
    resources :teams, only: [:index, :show, :create, :update, :destroy]
    resources :registrations, only: [:index, :show, :create, :destroy]
    resources :follows, only: [:index, :show, :create, :destroy]
    resources :team_memberships, only: [:index, :show, :create, :destroy]
    resources :images, only: [:index, :show, :create, :update, :destroy]
  end

  root to: "static_pages#root"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  after_initialize :ensure_session_token

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, length: { minimum: 4, maximum: 16 }
  validates :email, :session_token, uniqueness: true

  has_many :tournaments, foreign_key: :author_id, dependent: :destroy
  has_one :owned_team, foreign_key: :owner_id, class_name: :Team, dependent: :destroy
  has_many :registered_tournaments, through: :owned_team, source: :registered_tournaments
  has_many :follows, foreign_key: :follower_id, dependent: :destroy
  has_many :followed_tournaments, through: :follows, source: :tournament
  has_many :team_memberships, dependent: :destroy
  has_many :registered_teams, through: :team_memberships, source: :team

  def self.find_by_credentials(credential, password) # for new session
    if credential.include?("@")
      user = User.find_by_email(credential)
    else
      user = User.find_by_username(credential)
    end
    user && user.is_password?(password) ? user : nil
  end

  def reset_token! # reset session token for log in and log out
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password) # encrypt password
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password) # check password
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  protected
  def ensure_session_token # generate session token for new user
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user) # redirect to static pages in log_in method
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Hi</h1>

app/views/users/new.html.erb
<div class="user-session-container">
  <h1>Sign Up!</h1>

  <% if flash[:errors] %>
    <div class="errors alert alert-danger">
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>
      Username<br>
      <input type="text" name="user[username]" value="" placeholder="Username">
    </label>
    <br>
    <label>
      Email<br>
      <input type="text" name="user[email]" value="" placeholder="Email">
    </label>
    <br>
    <label>
      Password<br>
      <input type="password" name="user[password]" value="" placeholder="Password">
    </label>

    <br>
    <input type="submit" class="btn btn-info" value="Submit">
    <br><br>
    <%= link_to "Log In With Existing Account", new_session_url %>
  </form>
</div>