config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :tournaments, only: [:index, :show, :create, :update, :destroy]
    resources :teams, only: [:index, :show, :create, :update, :destroy]
    resources :registrations, only: [:index, :show, :create, :destroy]
    resources :follows, only: [:index, :show, :create, :destroy]
    resources :team_memberships, only: [:index, :show, :create, :destroy]
    resources :images, only: [:index, :show, :create, :update, :destroy]
  end

  root to: "static_pages#root"
end

app/views/layouts/_header.html.erb
<% if !logged_in? %>
  <div id="navbar">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TournaGen</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Log In", new_session_url %></li>
            <li><%= link_to "Sign Up", new_user_url %></li>
          </ul>
        </div> -->
      </div>
    </nav>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TournaGen</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style type="text/css" media="only screen and (max-width: 480px)">
    /* Mobile styles */
    @media only screen and (max-width: 480px) {
      table[class*="w320"] {
        width: 320px !important;
      }
    }
  </style>
  <script src="https://widget.cloudinary.com/global/all.js" type="text/javascript" charset="utf-8"></script>

  <script type="text/javascript" charset="utf-8">
    window.CLOUDINARY_OPTIONS = {
      cloud_name: "<%=ENV['CLOUD_NAME']%>",
      upload_preset: "<%= ENV['UPLOAD_PRESET'] %>"
    };
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-69411904-1', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>

</body>
</html>